builders:
  jet_builder:
    import: "package:jet_builder/builder.dart"
    builder_factories: [ "jetRouteGenerator" ]
    build_extensions: { ".dart": [ ".g.dart" ] }
    auto_apply: dependents
    build_to: source
